import assert from 'node:assert/strict';
import { _electron,chromium } from 'playwright';
import {createRequire} from 'node:module';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {startTimelineCandidate} from '../../../../tests/integration/timeline-ui-candidate.mjs';
import {localUiSession} from '../../../../tests/helpers/local-ui-session.mjs';
const out=resolve('tests/evidence/qa-3/scroll-focused');mkdirSync(out,{recursive:true});const checks=[];const env={...process.env};for(const k of Object.keys(env))if(/^(WEFTMATE_|MEMOWEFT_)/.test(k)||k==='ELECTRON_RUN_AS_NODE')delete env[k];
for(const theme of ['light','dark']){const f=await startTimelineCandidate({historyCount:20,interactive:true,inlineProgress:true,composer:true,baseTime:Date.now()-15000});const profile=mkdtempSync(join(tmpdir(),'weftmate-qa3-scroll-'));let app,browser;try{app=await _electron.launch({executablePath:createRequire(import.meta.url)('electron'),cwd:resolve('.'),args:['scripts/review-gallery/electron.mjs','--force-device-scale-factor=1'],env:{...env,REVIEW_PROFILE:profile,REVIEW_ORIGIN:f.origin,REVIEW_THEME:theme}});const desktop=await app.firstWindow();await localUiSession(desktop,f.credentials);browser=await chromium.launch({headless:true});const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await phone.goto(f.origin+'/personal/v1/ui');await localUiSession(phone,f.credentials);
for(const [surface,page]of [['desktop',desktop],['mobile-web',phone]]){const start=Date.now(),name=surface+'-'+theme;try{page.setDefaultTimeout(15000);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.evaluate(()=>{const b=document.getElementById('chat-scroll');b.scrollTop=b.scrollHeight});for(let i=0;i<14;i++)f.progress.text(`QA3 ${name} 长回复 ${i}：这是合成长文本，用于确认滚动阅读位置。\n\n`.repeat(4));await page.getByText(new RegExp(`QA3 ${name} 长回复 13`)).first().waitFor();await page.waitForFunction(()=>{const b=document.getElementById('chat-scroll');return b.scrollHeight-b.clientHeight-b.scrollTop<3});await page.screenshot({path:join(out,name+'-bottom.png')});await page.evaluate(()=>{const b=document.getElementById('chat-scroll');b.scrollTop=b.scrollHeight/3});await page.waitForTimeout(200);const prior=await page.evaluate(()=>document.getElementById('chat-scroll').scrollTop);f.progress.text(`QA3 ${name} 新内容：仍然保留正在阅读的历史。`);await page.getByText(new RegExp(`QA3 ${name} 新内容`)).first().waitFor();const after=await page.evaluate(()=>document.getElementById('chat-scroll').scrollTop);assert.ok(Math.abs(after-prior)<3);await page.screenshot({path:join(out,name+'-history.png')});const jump=page.getByRole('button',{name:'回到底部',exact:true});await jump.click();await page.waitForFunction(()=>{const b=document.getElementById('chat-scroll');return b.scrollHeight-b.clientHeight-b.scrollTop<3});await page.screenshot({path:join(out,name+'-returned.png')});checks.push({surface,theme,status:'passed',durationMs:Date.now()-start,historyMovementPx:after-prior,stickyBottom:true,jumpToBottom:true});}catch(e){checks.push({surface,theme,status:'failed',durationMs:Date.now()-start,error:e.message});await page.screenshot({path:join(out,name+'-failed.png')});}writeFileSync(join(out,'results.json'),JSON.stringify({realElectron:true,realHTTP:true,syntheticExecution:true,checks},null,2));}
}finally{await browser?.close();await app?.close();await f.close();rmSync(profile,{recursive:true,force:true});}}
console.log(JSON.stringify(checks));
