// Generated by services/cloud/scripts/build-mail-assets.mjs from the desktop design tokens.
export const mailTokens = {
  "light": {
    "canvas": "#faf9f7",
    "surface": "#fff",
    "ink": "#272724",
    "ink-secondary": "#575752",
    "ink-muted": "#676762",
    "line": "#e1e0db"
  },
  "dark": {
    "canvas": "#20211f",
    "surface": "#262724",
    "ink": "#e8e9e3",
    "ink-secondary": "#bbbdb4",
    "ink-muted": "#a0a397",
    "line": "#40423b"
  },
  "space": {
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "20": "20px",
    "24": "24px",
    "28": "28px",
    "32": "32px",
    "36": "36px"
  },
  "radius": {
    "12": "12px",
    "16": "16px"
  },
  "fontSize": {
    "10": "10px",
    "13": "13px",
    "15": "15px",
    "27": "27px",
    "36": "36px"
  },
  "fontFamily": {
    "body": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"PingFang SC\", \"Microsoft YaHei UI\", \"Microsoft YaHei\", \"Noto Sans CJK SC\", sans-serif",
    "mono-desktop": "Consolas, 'SFMono-Regular', monospace"
  },
  "lineHeight": {
    "1_25": "1.25",
    "1_65": "1.65"
  }
};
