import {readFileSync,writeFileSync,readdirSync,statSync,existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const root=resolve('tests/evidence/qa-5'),read=name=>JSON.parse(readFileSync(join(root,name),'utf8'));
const usage={requests:0,withUsage:0,missingUsage:0,inputTokens:0,cachedInputTokens:0,outputTokens:0,sources:[]};
for(const name of ['correction/results.json','smoke-flow-fixture/usage.json','smoke/usage.json']){if(!existsSync(join(root,name)))continue;const r=read(name);const rows=r.requests;const own={source:name,requests:rows.length,withUsage:0,missingUsage:0,inputTokens:0,outputTokens:0,cachedInputTokens:0};for(const row of rows){if(row.usage){own.withUsage++;own.inputTokens+=row.usage.prompt_tokens??0;own.outputTokens+=row.usage.completion_tokens??0;own.cachedInputTokens+=row.usage.prompt_tokens_details?.cached_tokens??0;}else own.missingUsage++;}for(const key of Object.keys(own))if(key!=='source')usage[key]+=own[key];usage.sources.push(own);}
usage.note='Actual MiMo proxy requests, including failed/cancelled attempts; synthetic exit/erasure and LAN requests excluded. Missing usage is not free usage. Not a bill.';writeFileSync(join(root,'usage-total.json'),JSON.stringify(usage,null,2));
const summary={baseline:read('baseline.json'),generatedAt:new Date().toISOString(),productDiff:execFileSync('git',['diff','--name-only','--','src','scripts','apps','package.json','package-lock.json'],{encoding:'utf8'}).trim()};
if(existsSync(join(root,'stability/results.json'))){const s=read('stability/results.json');summary.stability={cycles:s.checks.length,passed:s.checks.filter(x=>x.status==='passed').length,failed:s.checks.filter(x=>x.status!=='passed'),elapsedMs:s.stability?.elapsedMs,fatal:s.fatal};}
if(existsSync(join(root,'exit-matrix/results.json'))){const s=read('exit-matrix/results.json');summary.exitRows=s.rows.filter(r=>r.state!=='formation');}
for(const method of ['tray','task-manager-force','logout-taskkill'])if(existsSync(join(root,`exit-formation-${method}/results.json`)))summary.exitRows.push(...read(`exit-formation-${method}/results.json`).rows);
if(summary.exitRows)summary.exitRows=summary.exitRows.map(r=>({state:r.state,method:r.method,attempt:r.attempt,passed:r.passed,completedEventCount:r.completedEventCount,completedRetained:r.completedRetained,residualProcessCount:r.residualProcesses?.length,tmpAfterRecoveryCount:r.tmpAfterRecovery?.length,immediateHealth:r.healthImmediatelyAfterRestart?.state,healthRecoveryMs:r.healthRecoveryMs,health:r.health?.state,outbox:r.health?.pendingBoundaryCount,pending:r.health?.pendingFormationCount,error:r.error?.split('\n')[0]}));
writeFileSync(join(root,'summary.json'),JSON.stringify(summary,null,2));
const envValue=(name,scope)=>execFileSync('powershell.exe',['-NoProfile','-Command',`[Console]::Out.Write([Environment]::GetEnvironmentVariable('${name}','${scope}'))`],{encoding:'utf8',windowsHide:true}).trim();
const secrets=[envValue('MIMO_API_KEY','Machine'),envValue('WEFTMATE_LAN_MODEL_KEY','User'),envValue('WEFTMATE_LAN_MODEL_BASE_URL','User')].filter(Boolean);if(secrets[2]){try{secrets.push(new URL(secrets[2]).host);}catch{}}
const files=[];function walk(path){for(const e of readdirSync(path,{withFileTypes:true})){const p=join(path,e.name);if(e.isDirectory())walk(p);else files.push(p);}}walk(root);const hits=[];
for(const path of files){const buffer=readFileSync(path);for(let i=0;i<secrets.length;i++)if(buffer.includes(Buffer.from(secrets[i])))hits.push({file:path.slice(root.length+1),secretIndex:i});if(/\.(json|log|txt|md|jsonl)$/.test(path)&&/-----BEGIN (?:PRIVATE|RSA PRIVATE) KEY-----/.test(buffer.toString()))hits.push({file:path.slice(root.length+1),privateKey:true});}
writeFileSync(join(root,'privacy-scan.json'),JSON.stringify({at:new Date().toISOString(),fileCount:files.length,bytes:files.reduce((s,p)=>s+statSync(p).size,0),credentialOrLanHits:hits,passed:hits.length===0},null,2));if(hits.length)process.exitCode=1;
console.log(JSON.stringify({usage,privacyHits:hits.length,exitRows:summary.exitRows?.length,stability:summary.stability}));
