import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const base='tests/evidence/qa-6/';
const read=name=>existsSync(base+name)?JSON.parse(readFileSync(base+name,'utf8').replace(/^\uFEFF/,'')):null;
const sources=['smoke-initial-blocker/usage.json','smoke/usage.json','supplement/usage.json','approval-recheck/usage.json'];
const usage={model:'mimo-v2.6-flash',sources:[],requests:0,withUsage:0,missingUsage:0,inputTokens:0,cachedInputTokens:0,outputTokens:0,totalTokens:0,notABillingStatement:true};
for(const name of sources){const file=read(name);if(!file?.mimo)continue;const sum={file:name,requests:file.requests.length,withUsage:0,inputTokens:0,cachedInputTokens:0,outputTokens:0,totalTokens:0};for(const row of file.requests){if(!row.usage)continue;sum.withUsage++;sum.inputTokens+=row.usage.prompt_tokens??0;sum.cachedInputTokens+=row.usage.prompt_tokens_details?.cached_tokens??0;sum.outputTokens+=row.usage.completion_tokens??0;sum.totalTokens+=row.usage.total_tokens??0;}usage.sources.push(sum);for(const key of ['requests','withUsage','inputTokens','cachedInputTokens','outputTokens','totalTokens'])usage[key]+=sum[key];}
usage.missingUsage=usage.requests-usage.withUsage;writeFileSync(base+'usage-total.json',JSON.stringify(usage,null,2));
const perf=read('native-500/results.json')?.populations?.[0],exits=read('exit-formation-final/results.json'),smoke=read('smoke/results.json'),supplement=read('supplement/results.json');
const result={baseline:'480d65e462652a3111d2b40e09f697b2f78b8f8e',core:'233cc2f0b27a921a699a9c4c43b1a612375970f8',migrationAllowed:false,blockingIssues:['QA6-B01 first main-chat message rejected before native session creation','QA6-B02 installed project reader script remains inside app.asar'],performance:perf?{metrics:perf.metrics,listCpuPercent:perf.listCpuPercent,cpuPercent:perf.cpuPercent}:null,exitRecovery:exits?.rows.map(r=>({method:r.method,restartToProcessingMs:r.restartToProcessingMs,restartToHealthyMs:r.restartToHealthyMs,completedRetained:r.completedRetained,passed:r.passed})),durability:read('durable-review.json'),smoke:smoke?{elapsedMs:smoke.elapsedMs,checks:smoke.checks.map(({name,passed,error})=>({name,passed,...error?{error}:{}})),errors:smoke.errors,health:smoke.health,correctedPreferenceChecks:smoke.checks.filter(x=>/^daily-\d+$/.test(x.name)&&Number(x.name.split('-')[1])%2===1).map(x=>({name:x.name,apple:x.reply?.includes('苹果'),preferredName:x.reply?.includes('小织')}))}:null,supplement:supplement?.checks,approvalRecheck:read('approval-recheck/results.json'),migration:read('installed/migration-report.json'),upgrade:read('upgrade/results.json')?{passed:read('upgrade/results.json').passed,error:read('upgrade/results.json').error}:null,requiredTests:read('required-summary.json'),usage,cleanup:read('cleanup.json')};
writeFileSync(base+'summary.json',JSON.stringify(result,null,2));console.log(JSON.stringify({performance:result.performance,exitRecovery:result.exitRecovery,smokeChecks:smoke?.checks.length,supplementChecks:supplement?.checks.length,usage}));
