import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {randomUUID,createHash} from 'node:crypto';
import {harness,pause,until} from './harness.mjs';
const out=resolve('tests/evidence/qa-7/live');mkdirSync(out,{recursive:true});
const root=mkdtempSync(join(tmpdir(),'weftmate-qa7-install-')),installation=join(root,'Programs'),installer=resolve('.local/qa-7/releases/0.1.1-preview.7/build/WeftMate-Setup-0.1.1-preview.7.exe');
writeFileSync(resolve('.local/qa-7/install-root.txt'),root);
const report={baseline:'2a075c13',startedAt:new Date().toISOString(),checks:[],installerSha256:createHash('sha256').update(readFileSync(installer)).digest('hex')};
const save=()=>writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2));let h;
const t=Date.now();execFileSync(installer,['--updated','/S','/currentuser',`/D=${installation}`],{windowsHide:true,timeout:600000});report.installMs=Date.now()-t;save();
const executable=join(installation,'WeftMate.exe');writeFileSync(resolve('.local/qa-7/executable.txt'),executable);
try{
h=await harness('live',{mimo:true,direct:true,installed:executable});const p=h.page;
const shot=name=>p.screenshot({path:join(out,name+'.png')});
const check=async(name,fn)=>{try{report.checks.push({name,passed:true,...await fn()});console.log('PASS',name);}catch(e){report.checks.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);await shot(name+'-failed').catch(()=>{});}save();};
const active=async()=>{const row=p.locator('#session-list [data-session-id]:has(button.is-current)').first();const id=await row.count()?await row.getAttribute('data-session-id'):null;return id||(await h.api('/chats/main')).body.chat.activeSessionId;};
async function say(text,{approval=false,motion=false}={}){const beforeId=await active(),beforeSeq=beforeId?Math.max(-1,...(await h.events(beforeId)).map(e=>e.seq)):-1;const prior=new Set((await h.api('/commands?limit=100')).body.commands.map(c=>c.commandId));
if(motion)await p.bringToFront();if(motion)await p.evaluate(()=>{globalThis.qa7Frames=[];globalThis.qa7Sampling=true;const frame=()=>{if(!qa7Sampling)return;const msgs=[...document.querySelectorAll('.conversation-message,.timeline-message,.message')];qa7Frames.push({at:performance.now(),dot:!!document.querySelector('.reply-indicator'),streaming:document.querySelectorAll('.reply-streaming,[data-streaming="true"],.is-streaming').length,reduced:WeftReplyMotion.reduced,paused:WeftReplyMotion.paused,assistantCount:document.querySelectorAll('.message.assistant').length,assistantTextLength:[...document.querySelectorAll('.message.assistant .message-text')].at(-1)?.innerText.length||0,sheen:document.querySelectorAll('.reply-sheen').length,textLength:document.getElementById('conversation')?.innerText.length||document.body.innerText.length,hidden:document.hidden});requestAnimationFrame(frame);};requestAnimationFrame(frame);});
await p.locator('#message-text').fill(text);await p.locator('#send-message').click();
const command=await until(async()=>{const rows=(await h.api('/commands?limit=100')).body.commands;const c=rows.find(c=>!prior.has(c.commandId)&&['chat.message','session.message'].includes(c.kind));if(['rejected','failed'].includes(c?.state))throw Error('COMMAND_'+c.state+':'+c.errorCode);return c?.state==='accepted_by_dsh'&&c;},30000);
let approvals=0,orange=[],streamShot=false;
const ev=await until(async()=>{if(motion&&!streamShot){const seen=await p.locator('.reply-indicator,.reply-streaming').count();if(seen){await shot('motion-in-progress');streamShot=true;}}if(approval){const b=p.getByRole('button',{name:'批准',exact:true});if(await b.isVisible().catch(()=>false)){const toggle=p.locator('.sidebar-project-toggle[aria-expanded="true"]').first();if(await toggle.count())await toggle.click();orange.push(await p.locator('.project-group,.project-section,[data-project-id]').evaluateAll(ns=>ns.map(n=>({text:n.innerText,html:n.outerHTML.slice(0,3000)}))));await shot('project-pending-'+approvals);await b.click();approvals++;}}const rows=await h.events(command.sessionId);return rows.some(e=>e.type==='turn.ended'&&e.seq>(command.sessionId===beforeId?beforeSeq:-1))&&rows;},150000);
if(motion){report.motion=await p.evaluate(()=>{qa7Sampling=false;return qa7Frames;});await shot('motion-final');}
const after=ev.filter(e=>e.seq>(command.sessionId===beforeId?beforeSeq:-1));writeFileSync(join(out,'events-'+report.checks.length+'.json'),JSON.stringify(after,null,2));assert.ok(after.some(e=>e.type==='assistant.message'&&e.data.text?.trim()),'No assistant reply');assert.ok(after.some(e=>e.type==='turn.ended'&&e.data.reason==='completed'),'Turn did not complete');writeFileSync(join(out,'events-'+report.checks.length+'.json'),JSON.stringify(after,null,2));return {sessionId:command.sessionId,reply:after.filter(e=>e.type==='assistant.message').map(e=>e.data.text).join('\n'),approvals,orange};}
await h.api('/settings/models',{defaultModelProfileId:h.modelId},'PATCH');await p.reload();await p.locator('#assistant-view').waitFor();
p.on('requestfinished',async req=>{if(req.url().includes('/suggestions')){const r=await req.response();(report.suggestionRequests??=[]).push({path:new URL(req.url()).pathname,method:req.method(),request:req.postDataJSON(),status:r?.status(),response:await r?.json().catch(()=>null)});save();}});
await check('main-first',()=>say('你好，今天准备整理桌面资料，可以先给我一个简单建议吗？'));
for(const [i,text]of ['请记住一个合成偏好：我喝第973种花茶喜欢加一片柠檬。','整理资料时先分类还是先命名？请简短回答。','你记得我喝第973种花茶加什么吗？','纠正刚才的偏好：第973种花茶不加柠檬，改成加一片苹果，请记住。','现在花茶应该加什么？请简短回答。'].entries())await check('main-round-'+(i+1),async()=>{const r=await say(text);if([0,3].includes(i))r.memoryHealth=await h.healthy(90000);return r;});
await check('side-recall-corrected',async()=>{await p.getByRole('button',{name:'新旁聊 Ctrl N',exact:true}).click();const r=await say('我喝第973种花茶应该加什么？');assert.match(r.reply,/苹果/);await shot('side-recall');return r;});
await check('natural-stream',()=>say('请写一篇容易照做的家庭资料整理指南，包含分类、命名、备份和每周维护，并给一些例子。直接回答，不用工具。',{motion:true}));
await check('next-suggestions',async()=>{await p.locator('.next-suggestion-chip').first().waitFor({timeout:18000});await shot('next-suggestions');const chip=p.locator('.next-suggestion-chip').first(),text=await chip.textContent(),before=(await h.api('/commands?limit=100')).body.commands.length;await chip.click();assert.equal(await p.locator('#message-text').inputValue(),text);assert.equal((await h.api('/commands?limit=100')).body.commands.length,before);await p.locator('#message-text').fill('');return {fillOnly:true,text};});
await check('gray-completion',async()=>{await p.locator('#message-text').fill('请把刚才的整理建议');await p.locator('.composer-completion:not([hidden])').waitFor({timeout:18000});await shot('gray-completion');const text=await p.locator('.composer-completion-text').textContent();await p.locator('#message-text').press('Tab');assert.equal(await p.locator('#message-text').inputValue(),'请把刚才的整理建议'+text);await p.locator('#message-text').fill('');return {accepted:true,text};});await p.locator('#message-text').fill('');
const folder=join(h.root,'QA7-project');mkdirSync(folder);writeFileSync(join(folder,'source.txt'),'QA7_SYNTHETIC_PROJECT_SOURCE');
await check('folder-picker',async()=>{await p.getByRole('button',{name:'新旁聊 Ctrl N',exact:true}).click();await h.app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);await p.getByRole('button',{name:'添加文件夹',exact:true}).click();await p.getByRole('combobox',{name:'文件权限',exact:true}).click();await p.getByRole('option',{name:'可读写',exact:true}).click();await shot('folder-confirm');await p.getByRole('button',{name:'在这个文件夹里工作',exact:true}).click();await p.locator('.folder-confirm').waitFor({state:'detached'});return {projects:(await h.api('/projects')).body.projects};});
await check('project-read-write',async()=>{const id=await active();await h.api('/sessions/'+id+'/approval-mode',{mode:'ask'},'PATCH');const r=await say('请用文件工具读取项目里的source.txt，把原文写到approved.txt，再读回核对。只操作这个项目，不用shell。',{approval:true});assert.ok(r.approvals>0);assert.equal(readFileSync(join(folder,'approved.txt'),'utf8').trim(),'QA7_SYNTHETIC_PROJECT_SOURCE');r.artifacts=await until(async()=>{const a=await h.api('/library');return JSON.stringify(a).includes('approved.txt')&&a;},12000);await shot('project-complete');return r;});
await check('real-folder-drag',async()=>{await p.getByRole('button',{name:'新旁聊 Ctrl N',exact:true}).click();const dir=join(h.root,'QA7-dragged');mkdirSync(dir);const cdp=await p.context().newCDPSession(p),box=await p.locator('#message-text').boundingBox(),data={items:[],files:[dir],dragOperationsMask:1};for(const type of ['dragEnter','dragOver','drop'])await cdp.send('Input.dispatchDragEvent',{type,x:box.x+20,y:box.y+20,data});await p.locator('.folder-confirm').waitFor();await shot('real-drag-confirm');await p.getByRole('button',{name:'在这个文件夹里工作',exact:true}).click();await p.locator('.folder-confirm').waitFor({state:'detached'});await cdp.detach();return {realDirectoryDrag:true};});
await check('phone-web',async()=>await(await import('./phone.mjs')).run(h));
await check('android',async()=>{const sessions=(await h.api('/sessions')).body.sessions;const main=(await h.api('/chats/main')).body.chat;const side=sessions.find(s=>s.sessionId!==main.activeSessionId);if(side)await h.api('/sessions/'+side.sessionId+'/metadata',{unread:true},'PATCH');return await(await import('./android.mjs')).run(h);});
report.health=await h.healthy(90000).catch(e=>({error:e.message}));report.usage=await h.api('/usage').catch(()=>null);
}catch(e){report.fatal=e.stack;console.log('FATAL',e.message);}finally{if(h&&existsSync(join(h.profile,'personal-access/usage.json')))writeFileSync(join(out,'usage-ledger.json'),readFileSync(join(h.profile,'personal-access/usage.json')));await h?.close();save();}
report.installedSmokePreviouslyPassed=true;report.upgradePreviouslyPassed=true;
execFileSync(join(installation,'Uninstall WeftMate.exe'),['/S',`_?=${installation}`],{windowsHide:true,timeout:180000});report.uninstalled=true;rmSync(root,{recursive:true,force:true});if(h)rmSync(h.root,{recursive:true,force:true});report.finishedAt=new Date().toISOString();save();

