/* Named /personal/v1 data reads and writes for presentation components. */
globalThis.WeftUiCore.factories.client = (core) => {
    const write = (path, body, method = 'POST', options = {}) => core.accessApi(path, { method, protectedWrite: true, body, ...options });
    const authWrite = (path, body, method = 'POST') => core.api(path, { method, protectedWrite: true, body });
    return {
        taskSourcePath: (taskId, snapshotId) => `/tasks/${encodeURIComponent(taskId)}/sources/${encodeURIComponent(snapshotId)}`,
        artifactPreviewPath: artifactId => `/artifacts/${encodeURIComponent(artifactId)}/preview`,
        artifactDownloadUrl: artifactId => `${core.accessBase}/artifacts/${encodeURIComponent(artifactId)}/download`,
        historyImageUrl: (sessionId, attachmentId) => `${core.accessBase}/sessions/${sessionId}/attachments/${attachmentId}`,
        sessionAttachmentUrl: (sessionId, attachmentId) => `${core.accessBase}/sessions/${encodeURIComponent(sessionId)}/attachments/${encodeURIComponent(attachmentId)}`,
        syncAttachmentUrl: attachmentId => `${core.accessBase}/sync/attachments/${encodeURIComponent(attachmentId)}`,
        readHostStatus: () => core.accessApi('/status'),
        readProfile: () => core.api('/me'),
        saveProfile: body => authWrite('/profile', body, 'PATCH'),
        readDevices: () => core.api('/devices'),
        renameDevice: (id, name) => authWrite(`/devices/${encodeURIComponent(id)}`, { name }, 'PATCH'),
        revokeDevice: id => authWrite(`/devices/${encodeURIComponent(id)}`, undefined, 'DELETE'),
        readPendingDevices: () => core.accessApi('/cloud/devices/pending'),
        decideDevice: (id, decision) => write(`/cloud/devices/${encodeURIComponent(id)}/decision`, { decision }),
        readAccountModels: () => core.accessApi('/account/models'),
        saveAccountModel: (editing, body) => write(editing ? `/account/models/${encodeURIComponent(editing.id)}` : '/account/models', body, editing ? 'PATCH' : 'POST'),
        readProjects: () => core.accessApi('/projects'),
        registerProject: body => write('/projects', body),
        revokeProject: (id, requestId) => write(`/projects/${encodeURIComponent(id)}/revoke`, { requestId }),
        readBrowserWorkspace: () => core.accessApi('/workspaces/browser'),
        readDefaultApprovalMode: () => core.accessApi('/settings/approvals'),
        saveDefaultApprovalMode: mode => write('/settings/approvals', { mode }, 'PATCH'),
        saveBackgroundModel: backgroundModelProfileId => write('/settings/models', { backgroundModelProfileId }, 'PATCH'),
        restartService: key => write(`/system/${key}/restart`, {}, 'POST', { timeoutMs: 360000 }),
        readCommand: id => core.accessApi(`/commands/${encodeURIComponent(id)}`),
        logout: () => authWrite('/logout'),
        changePassword: (currentPassword, newPassword) => authWrite('/change-password', { currentPassword, newPassword }),
        readMemoryPage: params => core.memoryRequest(`/items?${params}`),
        readMemoryItem: (kind, id) => core.memoryRequest(`/items/${kind}/${core.memoryPathId(id)}`),
        readMemorySources: (kind, id) => core.memoryRequest(`/items/${encodeURIComponent(kind)}/${encodeURIComponent(id)}/sources`),
        requestMemoryCleanup: requestId => core.memoryRequest(`/commands/by-request/${encodeURIComponent(requestId)}/retry-cleanup`, { method: 'POST', body: {} }),
        submitMemoryCommand: (selected, operation, body) => core.memoryRequest(`/items/${selected.kind}/${core.memoryPathId(selected.id)}${operation === 'delete' ? '' : `/${operation}`}`, { method: operation === 'delete' ? 'DELETE' : 'POST', body }),
        readResource: path => core.accessApi(path),
        stopTask: (taskId, requestId) => core.accessApi(`/tasks/${encodeURIComponent(taskId)}/stop`, { method: 'POST', body: JSON.stringify({ requestId }) }),
        readTimelineDetail: (sessionId, seq) => core.accessApi(`/sessions/${encodeURIComponent(sessionId)}/events/${seq}/detail`),
        writePhoneEvents: events => write('/sync/events', { events }),
        readPhoneEvents: afterSeq => core.accessApi(`/sync/events?afterSeq=${afterSeq}&limit=100`),
    };
};
