/* ONB-1 Chinese resources. Extract this object when L10N-1 lands. */
globalThis.WeftOnboardingCopy = Object.freeze({
  mobileConnect: '连接你的电脑', mobileHelp: '在电脑的首次使用引导或设置 → 设备显示二维码；扫描或粘贴配对码，登录同一账号，然后在电脑上允许这台手机。', mobileWaiting: '回到电脑，在设备提示里允许这台手机。批准后会自动进入。',
  steps: ['欢迎', '账户', '选模型', '记忆', '导入历史', '连手机', '第一句话'],
  titles: ['你好，我是 WeftMate', '从这台电脑开始', '选一个一起工作的模型', '越聊，越了解你', '把过去带过来', '手机上，随时接着聊', '现在，说出第一句话'],
  descriptions: ['本地优先的个人助手：记得你，能在电脑上办事，手机上也能随时找到它。', '云账号让你的设备连在一起；也可以先把账户与资料留在这台电脑。', '模型由你自带。密钥保存在这台电脑的安全凭证中；使用云模型时，对话会发给所选提供方。', '对话和记忆是两回事。你可以查看、纠正，也可以让它忘掉。', '以后可以从 ChatGPT、Claude 等导出的聊天记录中形成带来源的记忆。导入前会先估算用量，由你确认。', '用手机扫描二维码，或在手机的连接页面粘贴配对码。新设备需要你在这台电脑上批准。', '从一个真实的小任务开始。点示例会填入输入框，由你发送。'],
  back: '返回', skip: '跳过这步', next: '继续', start: '开始聊天', later: '稍后设置', replay: '重新查看引导',
  progress: (index, total) => `首次使用引导，第 ${index + 1} 步，共 ${total} 步`,
  accountCloud: '注册 / 登录 WeftMate 云账号', accountLocal: '先离线使用这台电脑', accountDone: '账户已准备好，可以继续。', accountNeeded: '请先创建或登录账户，才能保存模型或连接手机。',
  preferredName: '怎么称呼你', nameHint: '可选，以后也可以在设置 → 个性化修改。', nameUnavailable: '个性化设置尚未就绪，可以稍后在设置里填写。',
  modelProvider: '模型提供方', modelAddress: '服务地址', modelId: '模型名称', modelKey: '粘贴密钥', modelName: '显示名称',
  advanced: '调整地址与模型', testMessage: '发送一条短消息验证（会使用模型额度）',
  getKey: '如何获取密钥', check: '测试连接', saveModel: '保存并使用这个模型', checking: '正在逐项检查连接…', saving: '正在保存模型…', modelSaved: '模型已保存，可以继续。', modelPending: '正在核对上次保存的模型…', modelUncertain: '模型保存结果待核对，请在设置 → 模型查看。',
  discover: '发现本机 / 局域网模型', discoveryHint: '只读取模型目录，不发送对话。扫描本机与已发现的局域网设备的常见模型端口；发现结果由你选择，不会自动添加。',
  additional: '补充服务地址（可选）', discoveryBusy: '正在寻找可用模型…', discoveryEmpty: '没有发现公开模型目录。请确认服务已启动，也可以填写地址后再试。', choose: '选择',
  localKeyHint: '没有设置密钥的本地服务可留空。', checkFirst: '请先测试连接并确认模型可用，再保存。', modelMissing: '还没有配置模型。可以跳过，回到聊天页后会提示设置。',
  memoryItems: [['会记住什么', '从普通对话里整理你的偏好、事实与决定，并保留来源。'], ['在哪里看', '在设置 → 记忆查看记住的内容和原话来源，也可以纠正。'], ['怎么忘', '在记忆页点「忘掉」；删除对话时，也可以选择忘掉它形成的记忆。'], ['这次别记', '新建临时对话，不形成新的记忆；已有记忆不会因此删除。']],
  healthLabel: text => text.replaceAll('宿主', '电脑'),
  healthLoading: '正在检查记忆健康…', healthError: '记忆健康暂时无法读取，可以稍后在设置里重试。', backfill: '整理过去的对话', backfillHint: '发现可整理的旧对话。先查看用量估算，确认后才会运行。',
  importSoon: '导入历史 · 即将支持', pair: '生成二维码 / 配对码', pairLoading: '正在准备配对…', pairCode: '手机配对码', pairQr: '连接这台电脑的二维码', pairRefresh: '二维码短时有效；过期后重新生成即可。以后也可以在设置 → 设备连接。', pairOffline: '离线账户可在同一网络用账户密码连接；绑定云账号后，可以扫码并批准手机。', deviceSettings: '打开设备设置',
  samples: ['帮我整理一个文件夹，先看看里面有什么，再给出整理方案。', '帮我查一份资料，核对来源后写成文档。', '帮我设一个提醒，先问我提醒内容和时间。'],
  noModel: '先添加一个模型，就能开始聊天。', configure: '设置模型', error: '操作未完成，请重试。',
  presets: [
    { id: 'mimo', name: 'MiMo', baseUrl: 'https://api.xiaomimimo.com/v1', modelId: 'mimo-v2.6-flash', help: '登录小米 MiMo 开放平台，在控制台创建密钥。', url: 'https://platform.xiaomimimo.com/' },
    { id: 'deepseek', name: 'DeepSeek', baseUrl: 'https://api.deepseek.com/v1', modelId: 'deepseek-chat', help: '登录 DeepSeek 开放平台，在 API keys 页面创建密钥。', url: 'https://platform.deepseek.com/api_keys' },
    { id: 'kimi', name: 'Kimi', baseUrl: 'https://api.moonshot.cn/v1', modelId: 'kimi-k2.5', help: '登录 Moonshot 开放平台，进入控制台的密钥管理。', url: 'https://platform.moonshot.cn/console/api-keys' },
    { id: 'qwen', name: '通义千问', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', modelId: 'qwen-plus', help: '在阿里云百炼创建密钥；请核对密钥所属地域与服务地址。', url: 'https://help.aliyun.com/zh/model-studio/get-api-key/' },
    { id: 'doubao', name: '豆包', baseUrl: 'https://ark.cn-beijing.volces.com/api/v3', modelId: '', help: '在火山方舟创建密钥并开通模型，填写模型名称或推理接入点。', url: 'https://www.volcengine.com/docs/82379/1399008' },
    { id: 'openai', name: 'OpenAI 兼容', baseUrl: 'https://api.openai.com/v1', modelId: '', help: '在所选服务的官方控制台创建密钥，并填写兼容服务地址与模型名称。', url: 'https://platform.openai.com/api-keys' },
    { id: 'anthropic', name: 'Anthropic 兼容', baseUrl: 'https://api.anthropic.com/v1', modelId: '', help: '在 Claude 控制台创建密钥，填写已开通的模型名称。使用官方 OpenAI 兼容接口，部分功能与原生接口不同。', url: 'https://platform.claude.com/docs/en/cli-sdks-libraries/libraries/openai-sdk' },
    { id: 'local', name: '本机 / 局域网', baseUrl: 'http://127.0.0.1:11434/v1', modelId: '', help: '启动本机或局域网的模型服务，开启 OpenAI 兼容接口，然后选择发现的模型。', url: 'https://docs.ollama.com/api/openai-compatibility' },
  ],
});
