/** One source: design/tokens/tokens.json. Run with npm run tokens:generate. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const tokens = JSON.parse(await readFile(join(root, 'design/tokens/tokens.json'), 'utf8'));
const check = process.argv.includes('--check');
const put = async (name, data) => {
  const path = join(root, name);
  if (check) {
    if (await readFile(path, 'utf8') !== data) throw new Error(`Stale generated tokens: ${name}`);
    return;
  }
  await mkdir(join(path, '..'), { recursive: true });
  await writeFile(path, data);
};
const kebab = name => name.replace(/[A-Z]/g, c => `-${c.toLowerCase()}`);
const entries = Object.entries;
const banner = 'Generated by scripts/generate-tokens.mjs; edit design/tokens/tokens.json.';
for (const [surface, path] of entries({ desktop: 'src/personal-access-ui', mobile: 'apps/mobile-ui/www' })) {
  const shared = entries(tokens.shared).flatMap(([group, values]) => entries(values)
    .map(([name, value]) => `  --wm-${kebab(group)}-${name}: ${value};`)).join('\n');
  const themes = tokens.surfaces[surface].themes.map(({ selector, variables }) =>
    `${selector} {\n${entries(variables).map(([name, value]) => `  ${name}: ${value};`).join('\n')}\n}`).join('\n');
  await put(`${path}/tokens.css`, `/* ${banner} */\n:root {\n${shared}\n}\n${themes}\n`);
}

const res = 'apps/android/app/src/main/res';
const androidName = name => `wm_${kebab(name).replaceAll('-', '_')}`;
const xml = body => `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${banner} -->\n<resources>\n${body}\n</resources>\n`;
const colors = { ...tokens.android.colors, brand: tokens.shared.color['brand-light'] };
await put(`${res}/values/design_colors.xml`, xml(entries(colors).map(([name, value]) =>
  `    <color name="${androidName(name)}">${value}</color>`).join('\n')));
// Only resources with an existing explicit theme counterpart vary in night mode.
await put(`${res}/values-night/design_colors.xml`, xml(
  `    <color name="wm_brand">${tokens.shared.color['brand-dark']}</color>`));
const dimensions = { ...tokens.android.dimensions,
  ...Object.fromEntries(entries(tokens.shared.radius).filter(([, v]) => v.endsWith('px'))
    .map(([name, value]) => [`radius${name}`, { value: parseFloat(value), unit: 'dp' }])) };
await put(`${res}/values/design_dimens.xml`, xml(entries(dimensions).map(([name, { value, unit }]) =>
  `    <dimen name="${androidName(name)}">${value}${unit}</dimen>`).join('\n')));
await put(`${res}/values/design_motion.xml`, xml(entries(tokens.shared.duration).map(([name, value]) =>
  `    <integer name="wm_duration_${name}">${Math.round(parseFloat(value) * (value.endsWith('ms') ? 1 : 1000))}</integer>`).join('\n') +
  '\n' + entries(tokens.shared.easing).map(([name, value]) =>
    `    <string name="wm_easing_${name}" translatable="false">${value}</string>`).join('\n')));
// The legacy native view helpers accept unitless dp/sp and context-free colours.
// Emit their existing API values too, without duplicating the authoritative data.
await put('apps/android/app/src/main/java/com/memoweft/weftmate/mobile/DesignTokens.kt',
  `// ${banner}\npackage com.memoweft.weftmate.mobile\n\nobject DesignTokens {\n` +
  entries(tokens.android.colors).map(([name, value]) =>
    `    const val native${name[0].toUpperCase() + name.slice(1)} = 0x${value.slice(1)}.toInt()`).join('\n') + '\n' +
  entries(dimensions).map(([name, { value, unit }]) => `    const val ${name} = ${value}${unit === 'sp' ? 'f' : ''}`).join('\n') + '\n' +
  entries(tokens.shared.duration).map(([name, value]) => {
    const millis = Math.round(parseFloat(value) * (value.endsWith('ms') ? 1 : 1000));
    return `    const val duration${name[0].toUpperCase() + name.slice(1)} = ${millis}L`;
  }).join('\n') + '\n}\n');

// Apple consumes this platform-neutral manifest in a later Mac work package.
// Keep the generated handoff outside apps/apple to avoid touching its live work.
await put('design/tokens/generated/apple/DesignTokens.json', JSON.stringify({
  format: 'weftmate.design-tokens.apple.v1', units: { dimensions: 'pt', duration: 'ms' },
  shared: tokens.shared, surfaces: tokens.surfaces, android: tokens.android,
}, null, 2) + '\n');
const dictionary = values => `[\n${entries(values).map(([name, value]) =>
  `        ${JSON.stringify(name)}: ${typeof value === 'string' ? JSON.stringify(value) : value}`).join(',\n')}\n    ]`;
const numeric = values => Object.fromEntries(entries(values).map(([name, value]) => [name, parseFloat(value)]));
const themeColors = {};
for (const [surface, { themes }] of entries(tokens.surfaces)) {
  for (const { selector, variables } of themes) {
    const name = surface + (selector.includes('dark') ? 'Dark' : 'Light') +
      (selector.match(/data-accent="(\w+)"/)?.[1] ?? '');
    themeColors[name] = Object.fromEntries(entries(variables).filter(([, value]) => value.startsWith('#')));
  }
}
await put('design/tokens/generated/apple/DesignTokens.swift',
  `// ${banner}\n// Native values are points / milliseconds; platform wiring is a separate Mac work package.\n` +
  `public enum WeftDesignTokens {\n` +
  entries({ spacing: numeric(tokens.shared.space), radius: numeric(Object.fromEntries(entries(tokens.shared.radius).filter(([, v]) => v.endsWith('px')))),
    fontSize: numeric(tokens.shared.fontSize), lineHeight: numeric(tokens.shared.lineHeight),
    durationMilliseconds: Object.fromEntries(entries(tokens.shared.duration).map(([name, value]) =>
      [name, parseFloat(value) * (value.endsWith('ms') ? 1 : 1000)])) })
    .map(([name, values]) => `    public static let ${name}: [String: Double] = ${dictionary(values)}`).join('\n') + '\n' +
  entries({ fontFamily: tokens.shared.fontFamily, fontRelative: tokens.shared.fontRelative,
    easing: tokens.shared.easing, shadowRecipes: tokens.shared.shadow,
    ...themeColors }).map(([name, values]) => `    public static let ${name}: [String: String] = ${dictionary(values)}`).join('\n') + '\n}\n');
console.log(`${check ? 'Checked' : 'Generated'} desktop/mobile CSS, Android resources/helpers and Apple token manifest.`);
