/** Generated assets have one source: design/icons. Run with npm run icons:generate. */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { _electron } from 'playwright';

// Apple-only refresh keeps the Mac work package within its platform scope.
if (process.argv.includes('--apple-only')) {
  await import('../apps/apple/Scripts/generate_icons.mjs');
  process.exit(0);
}

const root = resolve(import.meta.dirname, '..');
const source = join(root, 'design/icons');
const put = async (name, data) => { const path = join(root, name); await mkdir(join(path, '..'), { recursive: true }); await writeFile(path, data); };
const body = svg => svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>[\s\S]*?<\/title>/g, '');
const icons = Object.fromEntries(await Promise.all((await readdir(join(source, 'ui'))).filter(name => name.endsWith('.svg')).sort()
  .map(async name => [name.slice(0, -4), await readFile(join(source, 'ui', name), 'utf8')])));
// Existing native / mobile names stay compatible; new code uses canonical IDs.
const aliases = { menu: 'sidebar', close: 'deny', down: 'chevron', arrow: 'send', check: 'allow', user: 'account',
  device: 'desktop', pc: 'desktop', task: 'outputs', refresh: 'sync', shield: 'approval', warning: 'warn', browser: 'web',
  check_circle: 'approval', emulator: 'desktop', error: 'warn', export: 'download', external: 'open', heart: 'health',
  layers: 'outputs', link: 'source', notification_off: 'bell-off', panel: 'sidebar' };
for (const [name, svg] of Object.entries(icons)) await put(`apps/mobile-ui/www/icons/${name}.svg`, svg);
for (const [name, id] of Object.entries(aliases)) await put(`apps/mobile-ui/www/icons/${name}.svg`, icons[id]);
// Small mask consumers use the 16px optical weight, not a differently drawn icon.
for (const [name, svg] of Object.entries({ ...icons, ...Object.fromEntries(Object.entries(aliases).map(([a, b]) => [a, icons[b]])) }))
  await put(`apps/mobile-ui/www/icons/16/${name}.svg`, svg.replace('stroke-width="1.75"', 'stroke-width="1.5"'));
const shapes = Object.fromEntries(Object.entries(icons).map(([name, svg]) => [name, body(svg)]));
await put('src/personal-access-ui/icons.js', `/* Generated by scripts/generate-icons.mjs. */\n(() => {\n  const shapes = ${JSON.stringify(shapes, null, 2)};\n  globalThis.WeftIcons = { create(id, size = 20) {\n    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');\n    svg.setAttribute('viewBox', '0 0 24 24'); svg.setAttribute('aria-hidden', 'true');\n    svg.setAttribute('class', 'wm-icon'); svg.setAttribute('width', size); svg.setAttribute('height', size);\n    svg.setAttribute('fill', 'none'); svg.setAttribute('stroke', 'currentColor');\n    svg.setAttribute('stroke-width', size <= 16 ? '1.5' : '1.75');\n    svg.setAttribute('stroke-linecap', 'round'); svg.setAttribute('stroke-linejoin', 'round');\n    svg.innerHTML = shapes[id] || shapes.file; return svg;\n  } };\n})();\n`);
await put('src/personal-access-ui/icons.svg', `<svg xmlns="http://www.w3.org/2000/svg">${Object.entries(shapes).map(([id, s]) => `<symbol id="${id}" viewBox="0 0 24 24">${s}</symbol>`).join('')}</svg>\n`);

const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
const circle = (cx, cy, r) => `M${cx - r},${cy}a${r},${r} 0 1,0 ${2 * r},0a${r},${r} 0 1,0 ${-2 * r},0z`;
function pathData(tag, a) {
  if (tag === 'path') return a.d;
  if (tag === 'circle') return circle(+a.cx, +a.cy, +a.r);
  if (tag === 'rect') {
    const x = +a.x || 0, y = +a.y || 0, w = +a.width, h = +a.height, r = +a.rx || 0;
    return r ? `M${x+r},${y}h${w-2*r}a${r},${r} 0 0,1 ${r},${r}v${h-2*r}a${r},${r} 0 0,1 ${-r},${r}h${2*r-w}a${r},${r} 0 0,1 ${-r},${-r}v${2*r-h}a${r},${r} 0 0,1 ${r},${-r}z` : `M${x},${y}h${w}v${h}h${-w}z`;
  }
  throw new Error(`Unsupported SVG shape ${tag}`);
}
function vector(svg, { size = 24, viewport = 24, transform = '' } = {}) {
  const defaults = attrs(svg.match(/<svg[^>]*>/)[0]);
  const masks = Object.fromEntries([...svg.matchAll(/<mask[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/mask>/g)].map(m => {
    const cut = attrs(m[2].match(/<circle[^>]*>/)[0]);
    return [m[1], `M0,0h64v64H0z${circle(+cut.cx, +cut.cy, +cut.r)}`];
  }));
  const shapes = body(svg).replace(/<defs>[\s\S]*?<\/defs>/g, '');
  const paths = [...shapes.matchAll(/<(path|circle|rect)\b[^>]*\/?\s*>/g)].map(m => {
    const a = { ...defaults, ...attrs(m[0]) }, color = v => v === 'currentColor' ? '#FFFFFFFF' : v;
    const fill = a.fill && a.fill !== 'none' ? color(a.fill) : '#00000000';
    const stroke = a.stroke && a.stroke !== 'none' ? ` android:strokeColor="${color(a.stroke)}" android:strokeWidth="${a['stroke-width'] || 1.75}" android:strokeLineCap="round" android:strokeLineJoin="round"` : '';
    const opacity = a.opacity ? ` android:fillAlpha="${a.opacity}" android:strokeAlpha="${a.opacity}"` : '';
    const path = `<path android:pathData="${pathData(m[1], a)}" android:fillColor="${fill}"${stroke}${opacity}/>`;
    const mask = a.mask?.match(/url\(#(.+)\)/)?.[1];
    return mask ? `<group><clip-path android:pathData="${masks[mask]}" android:fillType="evenOdd"/>${path}</group>` : path;
  }).join('');
  return `<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="${size}dp" android:height="${size}dp" android:viewportWidth="${viewport}" android:viewportHeight="${viewport}">${transform ? `<group ${transform}>${paths}</group>` : paths}</vector>\n`;
}
const res = 'apps/android/app/src/main/res';
for (const file of (await readdir(join(root, res, 'drawable'))).filter(n => n.startsWith('wm_') && n.endsWith('.xml'))) {
  const id = file.slice(3, -4); const svg = icons[aliases[id] || id];
  if (!svg) throw new Error(`Missing native icon ${id}`);
  await put(`${res}/drawable/${file}`, vector(svg));
}
const light = await readFile(join(source, 'app/color-light.svg'), 'utf8');
const dark = await readFile(join(source, 'app/color-dark.svg'), 'utf8');
const mono = await readFile(join(source, 'app/monochrome.svg'), 'utf8');
for (const [id, svg] of [['color-light', light], ['color-dark', dark], ['monochrome', mono]]) {
  await put(`apps/mobile-ui/www/brand/${id}.svg`, svg);
  await put(`src/personal-access-ui/brand/${id}.svg`, svg);
}
await put('apps/mobile-ui/www/brand/weftmate-mark.svg', mono);
await put('src/personal-access-ui/favicon.svg', light);
await put(`${res}/drawable/weftmate_foreground.xml`, vector(light, { size: 108, viewport: 108, transform: 'android:translateX="22" android:translateY="22"' }));
await put(`${res}/drawable/weftmate_monochrome.xml`, vector(mono, { size: 108, viewport: 108, transform: 'android:translateX="22" android:translateY="22"' }));
await put(`${res}/drawable/ic_stat_weftmate.xml`, vector(mono, { size: 24, viewport: 64 }));
await put(`${res}/drawable/weftmate_background.xml`, '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108"><path android:pathData="M0,0h108v108H0z" android:fillColor="#FAF9F6"/></vector>\n');

// Use Chromium's SVG renderer shipped with the existing Electron dependency.
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const application = await _electron.launch({ executablePath: createRequire(import.meta.url)('electron'), args: [join(root, 'scripts/render-icons.cjs')], env });
try {
  const raster = async (svg, size) => Buffer.from(await application.evaluate(async (_electron, { svg, size }) => {
    await globalThis.iconRendererReady;
    return globalThis.iconRenderer.webContents.executeJavaScript(`new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = canvas.height = ${size}; canvas.getContext('2d').drawImage(image, 0, 0, ${size}, ${size}); resolve(canvas.toDataURL('image/png').split(',')[1]); }; image.onerror = reject; image.src = ${JSON.stringify('data:image/svg+xml;base64,' + Buffer.from(svg).toString('base64'))}; })`);
  }, { svg, size }), 'base64');
  const tile = light.replace(/(<svg[^>]*>)/, '$1<rect width="64" height="64" rx="13" fill="#FAF9F6"/>');
  const sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256];
  const pngs = [];
  for (const size of sizes) { const png = await raster(tile, size); pngs.push(png); await put(`src/assets/icons/app-${size}.png`, png); }
  const makeIco = images => {
    const header = Buffer.alloc(6 + sizes.length * 16); header.writeUInt16LE(1, 2); header.writeUInt16LE(sizes.length, 4);
    let offset = header.length;
    sizes.forEach((size, i) => { const index = 6 + i * 16; header[index] = header[index + 1] = size === 256 ? 0 : size; header.writeUInt16LE(1, index + 4); header.writeUInt16LE(32, index + 6); header.writeUInt32LE(images[i].length, index + 8); header.writeUInt32LE(offset, index + 12); offset += images[i].length; });
    return Buffer.concat([header, ...images]);
  };
  const ico = makeIco(pngs); await put('src/assets/icons/app.ico', ico); await put('build/icon.ico', ico);
  await put('build/icon.png', await raster(tile, 512));
  for (const [theme, color] of [['light', '#1B1D24'], ['dark', '#F1F2F6']]) {
    const png = await raster(mono.replaceAll('currentColor', color), 32);
    await put(`src/assets/icons/tray-${theme}.png`, png); await put(`build/tray-${theme}.png`, png);
    const images = [];
    for (const size of sizes) images.push(await raster(mono.replaceAll('currentColor', color), size));
    await put(`src/assets/icons/window-${theme}.ico`, makeIco(images));
  }
  await put('build/tray-icon.png', await raster(mono.replaceAll('currentColor', '#1B1D24'), 32));
  await put('src/assets/icons/notification.png', await raster(tile, 64));
  console.log(`Generated C4 app assets and ${Object.keys(icons).length} UI icons.`);
} finally { await application.close(); }

await import("../apps/apple/Scripts/generate_icons.mjs");
