import { applyMessageUpdate } from './message-stream-state.js';
import { appendMessageNode, updateMessageNode } from './message-dom-updates.js';
import { retryPromptForSession } from './session-retry.js';
import { deriveWorkspaceState } from './workspace-state.js';
import { captureThemeRollback, rollbackThemePreference } from './theme-preference-state.js';
import { beginApproval, receiveApproval, settleApproval } from './approval-state.js';
import { editorProfileForSettings } from './settings-editor-state.js';

const $ = (selector) => document.querySelector(selector);
const state = { configured: false, runtimeReady: false, profiles: [], activeId: null, sessions: [], current: null, messages: new Map(), lastPromptBySession: new Map(), pendingApproval: null, running: false, editingId: null, settingsTrigger: null };
let discoveryRevision = 0;

function activeProfile() { return state.profiles.find((item) => item.id === state.activeId) ?? null; }
function setText(selector, text) { $(selector).textContent = text; }
function setStatus(text, kind = '') { const node = $('#discovery-status'); node.textContent = text; node.dataset.kind = kind; }
function setError(text = '') { setText('#model-error', text); }
function setTheme(theme) { const value = ['light', 'dark'].includes(theme) ? theme : 'system'; document.documentElement.dataset.theme = value; try { localStorage.setItem('weftmate.theme', value); } catch {} }

function renderModelStatus() {
  const profile = activeProfile(); const hasKey = profile?.hasKey === true; const workspace = deriveWorkspaceState({ profile, runtimeReady: state.runtimeReady, running: state.running }); state.configured = workspace.configured;
  setText('#sidebar-model', profile?.name ?? '尚未添加模型');
  const connection = workspace.connection;
  setText('#sidebar-connection', connection);
  setText('#composer-model', profile ? `${profile.name} · ${profile.model}` : '未选择模型');
  setText('#connection', state.running ? '正在生成…' : (!profile ? '尚未添加模型' : !hasKey ? '当前模型缺少可用凭据' : !state.runtimeReady ? '模型运行时未就绪' : '已连接到 Harness'));
  const workspaceState = workspace.kind;
  const copy = workspaceState === 'no-profile' ? ['开始之前', '还没有模型', '你可以先浏览工作台。准备好后，在设置中通过真实服务发现并添加一个模型。', '添加模型']
    : workspaceState === 'credential-unavailable' ? ['需要凭据', '当前模型没有可用凭据', '请在设置中编辑当前模型并重新输入 API Key。', '编辑当前模型']
      : workspaceState === 'runtime-unavailable' ? ['需要恢复', '模型运行时未就绪', '历史对话仍会保留。请检查诊断或在设置中重新测试当前模型。', '打开设置'] : null;
  $('#no-model').hidden = !copy; $('#messages').hidden = false;
  if (copy) { setText('#workspace-eyebrow', copy[0]); setText('#workspace-title', copy[1]); setText('#workspace-description', copy[2]); $('#empty-add-model').textContent = copy[3]; }
  $('#prompt').disabled = !state.configured; $('#send').disabled = !state.configured;
  $('#prompt').placeholder = state.configured ? '向 WeftMate 交代任务…' : '先在设置中完成可用模型配置…';
  $('#new-chat').textContent = '新对话';
  $('#new-chat').disabled = !state.configured;
  $('#active-model').hidden = !profile;
  $('#retry').hidden = !(state.configured && state.current && retryPromptForSession(state.lastPromptBySession, state.messages, state.current));
}
function renderSessions() { const root = $('#session-list'); root.replaceChildren(...state.sessions.map((item) => { const button = document.createElement('button'); button.className = `session ${item.sessionId === state.current ? 'active' : ''}`; if (item.sessionId === state.current) button.setAttribute('aria-current', 'page'); button.textContent = item.title || '新对话'; button.onclick = () => selectSession(item.sessionId); return button; })); }
function shouldFollowStream() { const rail = $('#reading-rail'); return rail.scrollHeight - rail.scrollTop - rail.clientHeight < 40; }
function followStream(follow) { if (!follow) return; const rail = $('#reading-rail'); requestAnimationFrame(() => { rail.scrollTop = rail.scrollHeight; }); }
function messageNode(id) { return $('#messages').querySelector(`[data-message-id="${CSS.escape(id)}"]`); }
function announceMessage(text) { setText('#message-status', text); }
function createMessageNode(message) { const node = document.createElement('article'); node.dataset.messageId = message.id; node.className = `message ${message.kind}`; node.textContent = message.text; return node; }
function addMessage(kind, text) { if (!text || !state.current) return; const list = state.messages.get(state.current) ?? []; const follow = shouldFollowStream(); const update = applyMessageUpdate(list, kind, text, () => crypto.randomUUID()); state.messages.set(state.current, update.messages); if (update.mode === 'update') { const node = messageNode(update.message.id); if (node) updateMessageNode($('#messages'), update.message.id, update.message.text); else appendMessageNode($('#messages'), update.message, createMessageNode); if (update.announce) announceMessage(update.announce); followStream(follow); return; } if (update.mode === 'append') { appendMessageNode($('#messages'), update.message, createMessageNode); if (update.announce) announceMessage(update.announce); } }
function renderMessages(follow = shouldFollowStream()) { const root = $('#messages'); root.replaceChildren(...(state.messages.get(state.current) ?? []).map(createMessageNode)); followStream(follow); }
function setRunning(value) { state.running = value; $('#stop').disabled = !value; $('#send').hidden = value; $('#stop').hidden = !value; renderModelStatus(); }

async function refreshSessions() { const result = await window.weftmate.sessions(); state.sessions = result.items ?? []; renderSessions(); }
async function selectSession(sessionId) { state.current = sessionId; state.messages.set(sessionId, []); renderSessions(); renderMessages(); setRunning(false); const result = await window.weftmate.select(sessionId); if (!result.ok) addMessage('status', result.error); }
async function createSession() { if (!state.configured) return openSettings('new'); const result = await window.weftmate.create(); if (!result.ok) return addMessage('status', result.error); await refreshSessions(); await selectSession(result.sessionId); }
async function enterChat() { renderModelStatus(); if (!state.configured) return; await refreshSessions(); if (state.sessions.length) await selectSession(state.sessions[0].sessionId); else await createSession(); }

function renderModelList() { const root = $('#model-list'); root.replaceChildren(...state.profiles.map((profile) => { const row = document.createElement('button'); row.className = `model-row ${profile.id === state.editingId ? 'active' : ''}`; row.setAttribute('aria-current', profile.id === state.activeId ? 'true' : 'false'); row.innerHTML = `<strong></strong><small></small>`; row.querySelector('strong').textContent = profile.name; row.querySelector('small').textContent = `${profile.model}${profile.id === state.activeId ? ' · 当前' : profile.hasKey ? ' · 可切换' : ' · 凭据不可用'}`; row.onclick = () => fillEditor(profile); return row; })); }
function setSelectModels(models, selected = '') { const select = $('#model-name-select'); const available = [...new Set(models.filter((model) => typeof model === 'string' && model.length > 0))]; select.replaceChildren(...[new Option(available.length ? '选择服务实际返回的模型' : '请先获取模型列表', ''), ...available.map((model) => new Option(model, model))]); select.disabled = available.length === 0; select.value = available.includes(selected) ? selected : available.length === 1 ? available[0] : ''; return available; }
function invalidateDiscoveredModels() { const select = $('#model-name-select'); const hadModels = !select.disabled; const wasLoading = $('#discovery-status').dataset.kind === 'loading'; discoveryRevision += 1; setSelectModels([]); setError(); setStatus(hadModels || wasLoading ? '连接信息已更改，请重新获取模型列表。' : ''); }
function fillEditor(profile) { state.editingId = profile?.id ?? null; $('#model-id').value = profile?.id ?? ''; $('#editor-title').textContent = profile ? (profile.id === state.activeId ? '编辑当前模型' : '编辑模型') : '添加模型'; $('#model-provider').value = 'openai-compatible'; $('#model-name').value = profile?.name ?? ''; $('#model-base-url').value = profile?.baseUrl ?? ''; $('#model-api-key').value = ''; setSelectModels(profile ? [profile.model] : [], profile?.model); $('#delete-model').hidden = !profile; $('#test-model').hidden = !profile; $('#set-active-model').hidden = !profile || profile.id === state.activeId || profile.hasKey !== true; $('#set-active-model').disabled = false; $('#delete-confirm').hidden = true; setError(); setStatus(); renderModelList(); }
function openSettings(mode, trigger = document.activeElement) { state.settingsTrigger = trigger instanceof HTMLElement ? trigger : null; $('#settings').hidden = false; const conversation = $('#chat .conversation'); conversation.inert = true; conversation.setAttribute('aria-hidden', 'true'); $('#theme-select').value = document.documentElement.dataset.theme || 'system'; const selected = state.profiles.find((item) => item.id === state.editingId) ?? null; fillEditor(editorProfileForSettings(mode, activeProfile(), selected)); requestAnimationFrame(() => $('#close-settings').focus()); }
function closeSettings() { $('#settings').hidden = true; const conversation = $('#chat .conversation'); conversation.inert = false; conversation.removeAttribute('aria-hidden'); state.settingsTrigger?.focus?.(); }
function applyModels(view) { if (!view) return; state.profiles = view.profiles ?? state.profiles; state.activeId = view.activeId ?? null; if (typeof view.runtimeReady === 'boolean') state.runtimeReady = view.runtimeReady; renderModelStatus(); renderModelList(); }

$('#new-chat').onclick = createSession; $('#empty-add-model').onclick = () => openSettings(activeProfile() ? 'edit' : 'new'); $('#open-settings').onclick = () => openSettings(); $('#active-model').onclick = () => openSettings(); $('#close-settings').onclick = closeSettings; $('#new-model').onclick = () => fillEditor(null);
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !$('#settings').hidden) { event.preventDefault(); closeSettings(); } });
$('#model-provider').onchange = invalidateDiscoveredModels; $('#model-base-url').oninput = invalidateDiscoveredModels; $('#model-api-key').oninput = invalidateDiscoveredModels;
$('#theme-select').onchange = async (event) => { const theme = event.currentTarget.value; let stored = null; try { stored = localStorage.getItem('weftmate.theme'); } catch {} const previous = captureThemeRollback(document.documentElement.dataset.theme || 'system', stored); setText('#theme-error', ''); setTheme(theme); try { const result = await window.weftmate.setTheme(theme); if (!result?.ok) throw new Error(result?.error || '主题保存失败，已恢复原设置。'); } catch (error) { const rollback = rollbackThemePreference(previous); document.documentElement.dataset.theme = rollback.theme; try { if (rollback.storedTheme === null) localStorage.removeItem('weftmate.theme'); else localStorage.setItem('weftmate.theme', rollback.storedTheme); } catch {} event.currentTarget.value = rollback.theme; setText('#theme-error', error instanceof Error ? error.message : '主题保存失败，已恢复原设置。'); } };
$('#discover-models').onclick = async () => { const button = $('#discover-models'); const revision = ++discoveryRevision; const input = { id: $('#model-id').value || undefined, provider: $('#model-provider').value, baseUrl: $('#model-base-url').value.trim(), apiKey: $('#model-api-key').value.trim() }; setSelectModels([]); setError(); setStatus('正在连接服务并获取模型…', 'loading'); button.disabled = true; button.setAttribute('aria-busy', 'true'); button.textContent = '正在获取…'; try { const result = await window.weftmate.discoverModels(input); if (revision !== discoveryRevision) return; if (!result?.ok) { setStatus('获取失败', 'error'); setError(result?.error || '未能从服务获取模型列表。'); return; } const available = setSelectModels(Array.isArray(result.models) ? result.models : []); if (!available.length) { setStatus('获取失败', 'error'); setError('服务没有返回可用模型。'); return; } setStatus(`已获取 ${available.length} 个模型`, 'success'); if (available.length > 1) $('#model-name-select').focus(); } catch { if (revision !== discoveryRevision) return; setSelectModels([]); setStatus('获取失败', 'error'); setError('模型服务没有响应，请检查 API 地址、API Key 和网络后重试。'); } finally { button.disabled = false; button.removeAttribute('aria-busy'); button.textContent = '获取模型列表'; } };
$('#model-editor').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = Object.fromEntries(form); input.id = $('#model-id').value || undefined; setError(); $('#save-model').disabled = true; const result = await window.weftmate.saveModel(input); $('#save-model').disabled = false; if (!result.ok) return setError(result.error); applyModels(result.models); fillEditor(result.profile); setStatus('已保存并验证', 'success'); };
$('#test-model').onclick = async () => { if (!state.editingId) return; setError(); setStatus('正在验证…', 'loading'); const result = await window.weftmate.testModel(state.editingId); if (!result.ok) { setStatus('验证失败', 'error'); return setError(result.error); } setStatus('已通过真实验证', 'success'); };
$('#set-active-model').onclick = async () => { if (!state.editingId) return; setError(); setStatus('正在切换…', 'loading'); $('#set-active-model').disabled = true; const result = await window.weftmate.setActiveModel(state.editingId); $('#set-active-model').disabled = false; if (!result.ok) { setStatus('切换失败', 'error'); return setError(result.error); } applyModels(result.models); fillEditor(state.profiles.find((item) => item.id === state.editingId)); setStatus('已设为当前模型；已有会话保持原模型', 'success'); };
$('#delete-model').onclick = () => { if (!state.editingId) return; $('#delete-confirm').hidden = false; $('#confirm-delete').focus(); };
$('#cancel-delete').onclick = () => { $('#delete-confirm').hidden = true; $('#delete-model').focus(); };
$('#confirm-delete').onclick = async () => { if (!state.editingId) return; $('#confirm-delete').disabled = true; const result = await window.weftmate.deleteModel(state.editingId); $('#confirm-delete').disabled = false; if (!result.ok) { $('#delete-confirm').hidden = true; return setError(result.error); } applyModels(result.models); fillEditor(null); };
$('#export-diagnostics').onclick = async () => { setText('#export-status', '正在准备导出…'); const result = await window.weftmate.exportDiagnostics(); setText('#export-status', result.ok ? (result.canceled ? '已取消导出' : '已导出脱敏诊断') : result.error); };

$('#composer').addEventListener('submit', async (event) => { event.preventDefault(); if (!state.configured) return openSettings(activeProfile() ? 'edit' : 'new'); const input = $('#prompt'); const content = input.value.trim(); if (!state.current || !content) return; state.lastPromptBySession.set(state.current, content); input.value = ''; setRunning(true); const result = await window.weftmate.send({ sessionId: state.current, content }); if (!result.ok) { addMessage('status', result.error); setRunning(false); } });
$('#stop').onclick = async () => { if (!state.current) return; const result = await window.weftmate.cancel(state.current); if (!result.ok) addMessage('status', result.error); };
$('#retry').onclick = async () => { const content = state.current ? retryPromptForSession(state.lastPromptBySession, state.messages, state.current) : ''; if (!state.current || !content) return; setRunning(true); const result = await window.weftmate.send({ sessionId: state.current, content, mode: 'steer' }); if (!result.ok) { addMessage('status', result.error); setRunning(false); } };
async function resolveApproval(outcome) { const request = state.pendingApproval; if (!request) return; let approvalState = beginApproval({ request, error: '', submitting: false }); $('#approval-error').textContent = ''; $('#deny').disabled = true; $('#allow').disabled = true; try { let result = await window.weftmate.approval({ sessionId: state.current, rpcId: request.rpcId, approvalId: request.approvalId, outcome }); if (!result?.ok || result.accepted !== true) result = { ...result, ok: false, error: result?.error || '许可请求未被 Harness 接受。请重试或重新发起这项操作。' }; approvalState = settleApproval(approvalState, result); } catch { approvalState = settleApproval(approvalState, { ok: false, error: '许可请求未送达 Harness。请重试或重新发起这项操作。' }); } if (!approvalState.request) { $('#approval').hidden = true; state.pendingApproval = null; } else { $('#approval-error').textContent = approvalState.error; $('#approval').hidden = false; } if (state.pendingApproval === request) { $('#deny').disabled = false; $('#allow').disabled = false; } }
$('#deny').onclick = () => resolveApproval('rejected'); $('#allow').onclick = () => resolveApproval('allowed-once');
window.weftmate.onEvent((event) => { if (event.sessionId !== state.current) return; if (event.type === 'user.message') addMessage('user', event.data.text); else if (event.type === 'assistant.delta' || event.type === 'assistant.completed') addMessage(event.type, event.data.text); else if (event.type === 'turn.stopped') setRunning(false); else if (event.type === 'tool.approval-requested') { const approval = receiveApproval({ request: state.pendingApproval, error: '', submitting: false }, event.data); state.pendingApproval = approval.request; $('#approval-error').textContent = approval.error; setText('#approval-text', `Harness 请求执行 ${event.data.tool}。${event.data.reason ? ` ${event.data.reason}` : ''}`); $('#deny').disabled = false; $('#allow').disabled = false; $('#approval').hidden = false; } else if (event.type === 'tool.approval-resolved' && state.pendingApproval?.approvalId === event.data.approvalId) { $('#approval').hidden = true; state.pendingApproval = null; $('#approval-error').textContent = ''; } else if (event.type === 'tool.started') addMessage('status', `正在调用工具：${event.data.tool}`); else if (event.type === 'error') { addMessage('status', event.data.message); setRunning(false); } });
window.weftmate.onRuntimeError((value) => { state.runtimeReady = false; renderModelStatus(); addMessage('status', value.error); }); window.weftmate.onRuntimeReady(() => { state.runtimeReady = true; renderModelStatus(); if (state.current) selectSession(state.current); });
(async () => { const boot = await window.weftmate.bootstrap(); applyModels(boot); setTheme(boot.settings?.appearance?.theme ?? 'system'); await enterChat(); })();
