/**
 * Stage 2 projection from WeftMate's public model profiles to the pinned
 * `dsh-llm-pi-ai` configuration seam.  The generated overlay deliberately
 * contains route metadata and environment-variable references only: values
 * from safeStorage stay in Electron main memory and are injected into the one
 * managed DSH child environment.
 */
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { PublicModelProfile } from './stage2-config.ts';
export { DEFAULT_MODEL_CAPACITY, modelCapacityFor } from './model-budget.mjs';
import { modelCapacityFor } from './model-budget.mjs';
import { modelReasoning } from './model-reasoning.mjs';

export interface HarnessRoute {
  profileId: string;
  provider: string;
  apiKeyEnv: string;
}

export interface ModelCapacity {
  contextWindow: number;
  maxTokens: number;
}

function digest(profileId: string): string {
  return createHash('sha256').update(profileId, 'utf8').digest('hex');
}

/** Stable, path-safe identifiers.  No user-controlled text is used as a route or env name. */
export function routeForProfile(profileId: string): HarnessRoute {
  const value = digest(profileId);
  return {
    profileId,
    provider: `weftmate-${value.slice(0, 24)}`,
    apiKeyEnv: `WEFTMATE_LLM_KEY_${value.slice(0, 32).toUpperCase()}`,
  };
}

export function routeMap(profiles: readonly PublicModelProfile[]): Map<string, HarnessRoute> {
  return new Map(profiles.map((profile) => [profile.id, routeForProfile(profile.id)]));
}

function yaml(value: string): string { return JSON.stringify(value); }

/**
 * Render the *owned* CLI overlay. JSON string scalars are valid YAML scalars,
 * so endpoint/model/display text cannot become YAML syntax.  There is no
 * credential material in this output.
 */
export function renderModelRoutesPatch(profiles: readonly PublicModelProfile[]): string {
  // YAML's indented empty mapping form is significant here.  A bare
  // `providers:` becomes null, which the official configurable-provider
  // schema rightly rejects before the Models page can offer its first route.
  if (profiles.length === 0) {
    return [
      '# Generated by WeftMate Stage 2. This overlay contains no API keys.',
      '# It is passed with the official DSH --patch seam; do not hand-edit.',
      '- id: llm-pi-ai',
      '  config:',
      '    providers: {}',
      '',
    ].join('\n');
  }
  const lines = [
    '# Generated by WeftMate Stage 2. This overlay contains no API keys.',
    '# It is passed with the official DSH --patch seam; do not hand-edit.',
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
  ];
  for (const profile of profiles) {
    const route = routeForProfile(profile.id);
    const capacity = modelCapacityFor({ baseUrl: profile.baseUrl, modelId: profile.model });
    lines.push(
      `      ${route.provider}:`,
      `        displayName: ${yaml(profile.name)}`,
      `        apiKeyEnv: ${yaml(route.apiKeyEnv)}`,
      '        api: openai-completions',
      `        baseURL: ${yaml(profile.baseUrl)}`,
      '        models:',
      `          - id: ${yaml(profile.model)}`,
      `            name: ${yaml(profile.name)}`,
      `            contextWindow: ${capacity.contextWindow}`,
      `            maxTokens: ${capacity.maxTokens}`,
    );
    const reasoning = modelReasoning(profile);
    if (reasoning) {
      lines.push(`            reasoningEfforts: ${JSON.stringify(reasoning.reasoningEfforts)}`,
        `            compat: ${JSON.stringify(reasoning.compat)}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/** Atomic owned-file replacement.  A previous overlay remains intact on failure. */
export function writeModelRoutesPatch(filePath: string, profiles: readonly PublicModelProfile[]): void {
  const temporary = `${filePath}.${process.pid}.${randomUUID()}.tmp`;
  mkdirSync(dirname(filePath), { recursive: true });
  try {
    writeFileSync(temporary, renderModelRoutesPatch(profiles), { encoding: 'utf8', mode: 0o600 });
    renameSync(temporary, filePath);
  } catch (error) {
    try { rmSync(temporary, { force: true }); } catch { /* preserve prior overlay */ }
    throw error;
  }
}

/** Main-process-only child environment; values never leave this function. */
export function credentialEnvironment(
  profiles: readonly PublicModelProfile[],
  credentialFor: (profileId: string) => string | null | undefined,
  legacyCompatibilityProfile: PublicModelProfile | null,
): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const profile of profiles) {
    const credential = credentialFor(profile.id);
    if (!credential) continue;
    env[routeForProfile(profile.id).apiKeyEnv] = credential;
  }
  // Stage 1 sessions persist `deepseek-official`; retain its legacy process
  // contract while all Stage 2 sessions select their stable internal route.
  if (legacyCompatibilityProfile) {
    const credential = credentialFor(legacyCompatibilityProfile.id);
    if (credential) {
      env.DEEPSEEK_API_KEY = credential;
      env.DEEPSEEK_BASE_URL = legacyCompatibilityProfile.baseUrl;
    }
  }
  return env;
}
