/**
 * Stage 2 projection from WeftMate's public model profiles to the pinned
 * `dsh-llm-pi-ai` configuration seam.  The generated overlay deliberately
 * contains route metadata and environment-variable references only: values
 * from safeStorage stay in Electron main memory and are injected into the one
 * managed DSH child environment.
 */
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { PublicModelProfile } from './stage2-config.ts';

export interface HarnessRoute {
  profileId: string;
  provider: string;
  apiKeyEnv: string;
}

export interface ModelCapacity {
  contextWindow: number;
  maxTokens: number;
}

export const DEFAULT_MODEL_CAPACITY: Readonly<ModelCapacity> = Object.freeze({
  contextWindow: 262144,
  maxTokens: 32768,
});

/** Conservative decimal bounds within Xiaomi's published 1M context / 128K output.
 * Source: https://mimo.mi.com/models/mimo-v2.6-flash . These are model metadata,
 * not a turn budget, and explicit configured fields retain precedence. */
const MIMO_V26_FLASH_CAPACITY: Readonly<ModelCapacity> = Object.freeze({
  contextWindow: 1_000_000,
  maxTokens: 128_000,
});

export function modelCapacityFor(input: {
  baseUrl: string;
  modelId: string;
  contextWindow?: number;
  maxTokens?: number;
}): ModelCapacity {
  let officialMiMo = false;
  try {
    const destination = new URL(input.baseUrl);
    officialMiMo = destination.protocol === 'https:' &&
      destination.hostname === 'api.xiaomimimo.com' && destination.port === '';
  } catch { /* Unknown destinations retain the existing generic defaults. */ }
  const defaults = officialMiMo && input.modelId === 'mimo-v2.6-flash'
    ? MIMO_V26_FLASH_CAPACITY : DEFAULT_MODEL_CAPACITY;
  const capacity = {
    contextWindow: input.contextWindow ?? defaults.contextWindow,
    maxTokens: input.maxTokens ?? defaults.maxTokens,
  };
  for (const value of Object.values(capacity)) {
    if (!Number.isSafeInteger(value) || value <= 0) throw new TypeError('model capacity must contain positive safe integers');
  }
  return capacity;
}

function digest(profileId: string): string {
  return createHash('sha256').update(profileId, 'utf8').digest('hex');
}

/** Stable, path-safe identifiers.  No user-controlled text is used as a route or env name. */
export function routeForProfile(profileId: string): HarnessRoute {
  const value = digest(profileId);
  return {
    profileId,
    provider: `weftmate-${value.slice(0, 24)}`,
    apiKeyEnv: `WEFTMATE_LLM_KEY_${value.slice(0, 32).toUpperCase()}`,
  };
}

export function routeMap(profiles: readonly PublicModelProfile[]): Map<string, HarnessRoute> {
  return new Map(profiles.map((profile) => [profile.id, routeForProfile(profile.id)]));
}

function yaml(value: string): string { return JSON.stringify(value); }

/**
 * Render the *owned* CLI overlay. JSON string scalars are valid YAML scalars,
 * so endpoint/model/display text cannot become YAML syntax.  There is no
 * credential material in this output.
 */
export function renderModelRoutesPatch(profiles: readonly PublicModelProfile[]): string {
  // YAML's indented empty mapping form is significant here.  A bare
  // `providers:` becomes null, which the official configurable-provider
  // schema rightly rejects before the Models page can offer its first route.
  if (profiles.length === 0) {
    return [
      '# Generated by WeftMate Stage 2. This overlay contains no API keys.',
      '# It is passed with the official DSH --patch seam; do not hand-edit.',
      '- id: llm-pi-ai',
      '  config:',
      '    providers: {}',
      '',
    ].join('\n');
  }
  const lines = [
    '# Generated by WeftMate Stage 2. This overlay contains no API keys.',
    '# It is passed with the official DSH --patch seam; do not hand-edit.',
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
  ];
  for (const profile of profiles) {
    const route = routeForProfile(profile.id);
    lines.push(
      `      ${route.provider}:`,
      `        displayName: ${yaml(profile.name)}`,
      `        apiKeyEnv: ${yaml(route.apiKeyEnv)}`,
      '        api: openai-completions',
      `        baseURL: ${yaml(profile.baseUrl)}`,
      '        models:',
      `          - id: ${yaml(profile.model)}`,
      `            name: ${yaml(profile.name)}`,
      `            contextWindow: ${DEFAULT_MODEL_CAPACITY.contextWindow}`,
      `            maxTokens: ${DEFAULT_MODEL_CAPACITY.maxTokens}`,
    );
  }
  return `${lines.join('\n')}\n`;
}

/** Atomic owned-file replacement.  A previous overlay remains intact on failure. */
export function writeModelRoutesPatch(filePath: string, profiles: readonly PublicModelProfile[]): void {
  const temporary = `${filePath}.${process.pid}.${randomUUID()}.tmp`;
  mkdirSync(dirname(filePath), { recursive: true });
  try {
    writeFileSync(temporary, renderModelRoutesPatch(profiles), { encoding: 'utf8', mode: 0o600 });
    renameSync(temporary, filePath);
  } catch (error) {
    try { rmSync(temporary, { force: true }); } catch { /* preserve prior overlay */ }
    throw error;
  }
}

/** Main-process-only child environment; values never leave this function. */
export function credentialEnvironment(
  profiles: readonly PublicModelProfile[],
  credentialFor: (profileId: string) => string | null | undefined,
  legacyCompatibilityProfile: PublicModelProfile | null,
): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const profile of profiles) {
    const credential = credentialFor(profile.id);
    if (!credential) continue;
    env[routeForProfile(profile.id).apiKeyEnv] = credential;
  }
  // Stage 1 sessions persist `deepseek-official`; retain its legacy process
  // contract while all Stage 2 sessions select their stable internal route.
  if (legacyCompatibilityProfile) {
    const credential = credentialFor(legacyCompatibilityProfile.id);
    if (credential) {
      env.DEEPSEEK_API_KEY = credential;
      env.DEEPSEEK_BASE_URL = legacyCompatibilityProfile.baseUrl;
    }
  }
  return env;
}
